[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://www.waibug.com/*"
  to = "https://waibug.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://waib.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$DEPLOY_ID--waib.netlify.app"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "https://$BRANCH--waib.netlify.app"
